name: tesoro_regional_qr_generator
description: Generador de códigos QR para la app Tesoro Regional
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.3
  args: ^2.4.2
  qr: ^3.0.1
  image: ^4.0.17

dev_dependencies:
  lints: ^2.0.0
